# Codebook

## Description  
This is the codebook describing the data contained into [subject_tidy.csv](https://github.com/mtarantino/GettingAndCleaningData/blob/master/subject_tidy.csv) file created using the script [run_analysis.R](https://github.com/mtarantino/GettingAndCleaningData/blob/master/run_analysis.R). The dataset described for each observation defines a subject (defined by subject_id), an activity (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) a set (test or train) and features variables described in the below section.

## Features info

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

* tBodyAcc-XYZ  
* tGravityAcc-XYZ  
* tBodyAccJerk-XYZ  
* tBodyGyro-XYZ  
* tBodyGyroJerk-XYZ  
* tBodyAccMag  
* tGravityAccMag  
* tBodyAccJerkMag  
* tBodyGyroMag  
* tBodyGyroJerkMag  
* fBodyAcc-XYZ  
* fBodyAccJerk-XYZ  
* fBodyGyro-XYZ  
* fBodyAccMag  
* fBodyAccJerkMag  
* fBodyGyroMag  
* fBodyGyroJerkMag  

The set of variables that were estimated from these signals are: 

 * mean(): Mean value  
 * std(): Standard deviation  
 
# Variables list

Variable name  | Description | Unit
------------- | ------------- |  -------
subject_id | Subject ID | Integer
Activity  | Activity | Categorical : WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
set  | subject set | Categorical : test or train
tBodyAcc-mean()-X |  See Feature info section   | float ( see Features info for unit detailed)
tBodyAcc-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyAcc-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
tGravityAcc-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
tGravityAcc-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
tGravityAcc-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerk-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerk-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerk-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyro-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyro-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyro-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerk-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerk-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerk-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
tGravityAccMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerkMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerkMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-meanFreq()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-meanFreq()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-meanFreq()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-meanFreq()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-meanFreq()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-meanFreq()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-mean()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-mean()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-mean()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-meanFreq()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-meanFreq()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-meanFreq()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccMag-meanFreq() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyAccJerkMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyAccJerkMag-meanFreq() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyGyroMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyGyroMag-meanFreq() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyGyroJerkMag-mean() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyGyroJerkMag-meanFreq() |    See Feature info section | float ( see Features info for unit detailed)
tBodyAcc-std()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyAcc-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyAcc-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
tGravityAcc-std()-X |    See Feature info section | float ( see Features info for unit detailed)
tGravityAcc-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
tGravityAcc-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerk-std()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerk-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerk-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyro-std()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyro-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyro-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerk-std()-X |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerk-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerk-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccMag-std() |    See Feature info section | float ( see Features info for unit detailed)
tGravityAccMag-std() |    See Feature info section | float ( see Features info for unit detailed)
tBodyAccJerkMag-std() |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroMag-std() |    See Feature info section | float ( see Features info for unit detailed)
tBodyGyroJerkMag-std() |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-std()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyAcc-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-std()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccJerk-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-std()-X |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-std()-Y |    See Feature info section | float ( see Features info for unit detailed)
fBodyGyro-std()-Z |    See Feature info section | float ( see Features info for unit detailed)
fBodyAccMag-std() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyAccJerkMag-std() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyGyroMag-std() |    See Feature info section | float ( see Features info for unit detailed)
fBodyBodyGyroJerkMag-std() |  See Feature info section | float ( see Features info for unit detailed)